Pacific-Agency/nuxt-utils

README.md

Обновление `README`

---

.github/CODEOWNERS

Добавление `CODEOWNERS`

---

.github/workflows/update-package-json.yml

Добавление авторизации при релизе

---

.github/workflows/ci.yml
.github/workflows/gh-pages.yml
.github/workflows/release-package.yml
package.json
pnpm-lock.yaml

Обновление `pnpm` до `v8.1.0`

---

.nuxtrc
package.json
playground/app.vue
pnpm-lock.yaml
src/runtime/api/sitemap-routes.ts
src/runtime/composables/useScrollLock.ts
src/runtime/composables/useSubmitForm.ts
tsconfig.json

Замена автоимпорта на явный

---

src/module.ts
src/runtime/api/sitemap-routes.ts

Не работает эндпоинт для `Sitemap`

---

src/runtime/api/sitemap-routes.ts

Обработка ошибки 404 для `Sitemap`

---

docs/composables/use-submit-form.md
src/runtime/composables/useSubmitForm.ts

Реактивный параметр `url` для `useSubmitForm`

---

README.md
docs/.vitepress/config.ts
docs/index.md
docs/installation.md

Порядок установки и использования в документации

---

src/runtime/composables/useFetchAuth.ts

Отсутствует `credentials="include"` в `useFetchAuth`

---

src/runtime/composables/useFetchAuth.ts

Неправильный тип ответа от `useFetchAuth`

---

src/runtime/composables/useFetchAuth.ts

- Fix #78
Также это исправляет проблему выставления `POST` для запросов.

Рефактор параметров `useFetchAuth`

---

src/runtime/composables/useFetchAuth.ts

Неправильно определен тип `url` в `useFetchAuth`

---

src/runtime/composables/useFetchAuth.ts

Неправильный порядок параметров `defu` в `useFetchAuth`

---

.github/workflows/ci.yml
.github/workflows/update-package-json.yml

Использование общего репозитория `workflows`

---

src/runtime/composables/useSubmitForm.ts

Функция `useSubmitForm` возвращает `undefined` вместо ошибки

---

.github/workflows/update-package-json.yml

Отсутствует `BOT_ACCESS_TOKEN` в `workflows`

---

src/runtime/components/UtilsInput.vue

fix: Неправильно типизирован `v-model` у инпутов

---

docs/components/input-masked.md
docs/components/input.md
docs/components/password.md
docs/components/phone.md
docs/components/textarea.md

docs: Обновление документации включения `defineModel`

---

docs/.vitepress/config.ts
docs/composables/use-scroll-slider.md
src/runtime/composables/useScrollSlider.ts
src/runtime/composables/useSubmitForm.ts

feat: Функция `useScrollArrows`

---

docs/composables/use-scroll-slider.md
src/runtime/composables/useScrollSlider.ts

fix: Замена названий переменных крайнего правого и левого края

---

.npmrc
docs/.vitepress/config.ts
docs/composables/use-pagination.md
package.json
pnpm-lock.yaml
src/runtime/composables/usePagination.ts

feat: Функция `usePagination`

---

docs/composables/use-sanitize.md

В документацию добавлена информация о необходимости параметра `optimizeDeps` в конфиге.

docs: Информация об `optimizeDeps` в `useSanitize`

---

docs/components/input-masked.md
docs/components/map-widget.md
src/runtime/components/UtilsMapWidget.vue
tests/components/UtilsMapWidget.spec.ts

В компонент `UtilsMapWidget` добавлен опциональный пропс `locale`, который позволяет выбирать язык карты.
Также обновлены тесты и документация.

fix: Возможность выбора локализации `UtilsMapWidget`

---

src/runtime/components/UtilsInput.vue

Для `UtilsInput` добавлена возможность выбора типа `search`, который автоматически добавляет кнопку очистки поля.

fix: Добавление типа `search` для `UtilsInput`

---

src/runtime/components/UtilsMapWidget.vue
tests/components/UtilsMapWidget.spec.ts

DEVDES-699
Добавление масштаба в карту и обновление тестов.

fix: Добавление масштаба в карту

---

tests/components/UtilsInput.spec.ts
tests/components/UtilsInputMasked.spec.ts
tests/components/UtilsPassword.spec.ts
tests/components/UtilsPhone.spec.ts
tests/components/UtilsTextArea.spec.ts
tests/composables/usePhoneFormatter.spec.ts
tests/composables/usePriceFormatter.spec.ts
tests/setup.ts
vitest.config.ts

- Добавление параллельности у тестов
- Добавление компонента `Icon`

test: Обновление тестов

---

docs/api/sitemap.md
src/runtime/api/sitemap-routes.ts

Обновление эндпоинта для использования модуля `@nuxtjs/sitemap`.

feat!: Обновление эндпоинта `Sitemap`

---

docs/composables/use-submit-form.md
src/runtime/composables/useSubmitForm.ts

Fix #112.
Переработка функции для большей кастомизации:
- ⚠️ Удаление префикса `/mail/` из ссылки
- ⚠️ Изменение названий параметров
- Добавление возможности авторизации
- Обновление документации

feat!: Переработка фукнции `useSubmitForm`

---

src/runtime/components/UtilsPhone.vue

Добавление props placeholder в компоненте `UtilsPhone`, для того чтобы значение placeholder у поля можно было менять, если не передавать в него ничего, то по дефолту будет значение - +7 999 888-77-66

feat: Добавление props placeholder в компоненте `UtilsPhone`

---

.github/workflows/changelog.yml
.github/workflows/ci.yml
package.json
pnpm-lock.yaml
src/runtime/components/UtilsInputMasked.vue
src/runtime/components/UtilsPhone.vue
tests/components/UtilsInputMasked.spec.ts

Обновление всех зависимостей. Важные изменения:
- Обновление `maska` до `v3`
- Обновление `@nuxt/icon` до `v1`

feat!: Обновление зависимостей

---

.eslintignore
.github/workflows/publish.yml
docs/.vitepress/theme/index.ts
eslint.config.mjs
package.json
pnpm-lock.yaml
src/runtime/components/UtilsInput.vue
src/runtime/components/UtilsInputMasked.vue
src/runtime/components/UtilsPassword.vue
src/runtime/components/UtilsPhone.vue
src/runtime/components/UtilsTextArea.vue
src/runtime/composables/useFetchAuth.ts
src/runtime/composables/usePagination.ts
src/runtime/composables/usePhoneFormatter.ts
src/runtime/composables/useScrollSlider.ts
src/runtime/composables/useSubmitForm.ts
tests/components/UtilsInput.spec.ts
tests/components/UtilsInputMasked.spec.ts
tests/components/UtilsMapWidget.spec.ts
tests/components/UtilsPassword.spec.ts
tests/components/UtilsPhone.spec.ts
tests/components/UtilsTextArea.spec.ts
tests/composables/useHighlightedText.spec.ts

Обновление конфигураций ESLint и Prettier на `@exer7um`.
Также исправлена fix #180.

fix: Обновление конфигураций ESLint и Prettier

---

.eslintrc
docs/.vitepress/theme/index.ts
package.json
pnpm-lock.yaml
src/runtime/components/UtilsMapWidget.vue
src/runtime/composables/useFetchAuth.ts
src/runtime/composables/useHighlightedText.ts
src/runtime/composables/usePhoneFormatter.ts
src/runtime/composables/usePriceFormatter.ts
tests/components/UtilsDate.spec.ts
tests/components/UtilsInput.spec.ts
tests/components/UtilsInputMasked.spec.ts
tests/components/UtilsMapWidget.spec.ts
tests/components/UtilsPassword.spec.ts
tests/components/UtilsPhone.spec.ts
tests/components/UtilsTextArea.spec.ts
tests/composables/useHighlightedText.spec.ts
tests/composables/usePhoneFormatter.spec.ts
tests/composables/usePriceFormatter.spec.ts
tests/fixtures/basic/app.vue
tests/fixtures/basic/server/routes/sitemap.ts
vitest.config.ts

Обновление `@exer7um/eslint-config` до последней версии и исправление ошибок.

fix: Обновление конфигурации ESLint

---

.vscode/settings.json
docs/composables/use-fetch-auth.md
docs/installation.md
package.json
pnpm-lock.yaml
src/module.ts
src/runtime/plugins/openFetch.ts

Плагин для добавления авторизации к библиотеке `nuxt-open-fetch`.

feat: Авторизация для `nuxt-open-fetch`

---

src/runtime/composables/useSubmitForm.ts

Теперь поле `submitFormBody` может быть реактивным

fix: Поле `submitFormBody` может быть реактивным
